//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleSet
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Keyword { get; set; }
        public string Tags { get; set; }
        public string Focused { get; set; }
        public bool Recommended { get; set; }
        public int PagePosition { get; set; }
        public bool Enabled { get; set; }
        public string Author { get; set; }
        public string PraiseNum { get; set; }
        public string ViewNum { get; set; }
        public string CoverImagePath { get; set; }
        public string CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public string RelateProductId { get; set; }
        public string CategoryId { get; set; }
    }
}
