//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTime.DataLayer.MailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 receiveMailAddress 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmal", ReplyAction="*")]
        OnTime.DataLayer.MailService.SendEmalResponse SendEmal(OnTime.DataLayer.MailService.SendEmalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmal", ReplyAction="*")]
        System.Threading.Tasks.Task<OnTime.DataLayer.MailService.SendEmalResponse> SendEmalAsync(OnTime.DataLayer.MailService.SendEmalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmal", Namespace="http://tempuri.org/", Order=0)]
        public OnTime.DataLayer.MailService.SendEmalRequestBody Body;
        
        public SendEmalRequest() {
        }
        
        public SendEmalRequest(OnTime.DataLayer.MailService.SendEmalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receiveMailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bodyInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SendEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SendPassword;
        
        public SendEmalRequestBody() {
        }
        
        public SendEmalRequestBody(string receiveMailAddress, string subject, string bodyInfo, string SendEmail, string SendPassword) {
            this.receiveMailAddress = receiveMailAddress;
            this.subject = subject;
            this.bodyInfo = bodyInfo;
            this.SendEmail = SendEmail;
            this.SendPassword = SendPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmalResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnTime.DataLayer.MailService.SendEmalResponseBody Body;
        
        public SendEmalResponse() {
        }
        
        public SendEmalResponse(OnTime.DataLayer.MailService.SendEmalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEmalResult;
        
        public SendEmalResponseBody() {
        }
        
        public SendEmalResponseBody(bool SendEmalResult) {
            this.SendEmalResult = SendEmalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : OnTime.DataLayer.MailService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<OnTime.DataLayer.MailService.WebServiceSoap>, OnTime.DataLayer.MailService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnTime.DataLayer.MailService.SendEmalResponse OnTime.DataLayer.MailService.WebServiceSoap.SendEmal(OnTime.DataLayer.MailService.SendEmalRequest request) {
            return base.Channel.SendEmal(request);
        }
        
        public bool SendEmal(string receiveMailAddress, string subject, string bodyInfo, string SendEmail, string SendPassword) {
            OnTime.DataLayer.MailService.SendEmalRequest inValue = new OnTime.DataLayer.MailService.SendEmalRequest();
            inValue.Body = new OnTime.DataLayer.MailService.SendEmalRequestBody();
            inValue.Body.receiveMailAddress = receiveMailAddress;
            inValue.Body.subject = subject;
            inValue.Body.bodyInfo = bodyInfo;
            inValue.Body.SendEmail = SendEmail;
            inValue.Body.SendPassword = SendPassword;
            OnTime.DataLayer.MailService.SendEmalResponse retVal = ((OnTime.DataLayer.MailService.WebServiceSoap)(this)).SendEmal(inValue);
            return retVal.Body.SendEmalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnTime.DataLayer.MailService.SendEmalResponse> OnTime.DataLayer.MailService.WebServiceSoap.SendEmalAsync(OnTime.DataLayer.MailService.SendEmalRequest request) {
            return base.Channel.SendEmalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnTime.DataLayer.MailService.SendEmalResponse> SendEmalAsync(string receiveMailAddress, string subject, string bodyInfo, string SendEmail, string SendPassword) {
            OnTime.DataLayer.MailService.SendEmalRequest inValue = new OnTime.DataLayer.MailService.SendEmalRequest();
            inValue.Body = new OnTime.DataLayer.MailService.SendEmalRequestBody();
            inValue.Body.receiveMailAddress = receiveMailAddress;
            inValue.Body.subject = subject;
            inValue.Body.bodyInfo = bodyInfo;
            inValue.Body.SendEmail = SendEmail;
            inValue.Body.SendPassword = SendPassword;
            return ((OnTime.DataLayer.MailService.WebServiceSoap)(this)).SendEmalAsync(inValue);
        }
    }
}
