//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainEntities.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceDbModelContainer : DbContext
    {
        public FinanceDbModelContainer()
            : base("name=FinanceDbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           // modelBuilder.Properties<int>().Configure(p=>p.ha);
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Finance_Article { get; set; }
        public virtual DbSet<Event> Finance_Event { get; set; }
        public virtual DbSet<Index> Finance_Index { get; set; }
        public virtual DbSet<IndexData> Finance_IndexData { get; set; }
        public virtual DbSet<Message> Finance_Message { get; set; }
        public virtual DbSet<Goods> Finance_Goods { get; set; }
        public virtual DbSet<Dictionary> DictionarySet { get; set; }
    }
}
